// Translations file - updated
export const translations = {
    'es': {
        // Chat Overlay
        'my_projects': 'Mis Proyectos',
        'manage_workspaces': 'Gestiona y crea nuevos espacios de trabajo.',
        'create_project': 'Crear Proyecto',
        'no_projects': 'No tienes proyectos creados aún.',
        'new': 'Nuevo',
        'library': 'Biblioteca',
        'no_projects_sidebar': 'No hay proyectos',
        'new_folder_sidebar': 'Crear Proyecto',
        'storage': 'Almacenamiento',
        'new_chat': 'Nuevo Chat',
        'history': 'Historial',
        'no_history': 'No hay historial reciente',
        'ask_anything': 'Pregunta cualquier cosa...',
        'upload_files': 'Cargar archivos',
        'search_projects': 'Buscar proyectos por nombre',
        'add_kpi': 'Añadir KPI',
        'search_file': 'Buscar carpeta o archivo por nombre',
        'navigation': 'Navegación',
        'home': 'Inicio',
        'filter': 'Filtro',
        'click_upload': 'Haz clic aquí para cargar tu archivo o carpeta arrástralo.',
        'supports_files': 'Soporta carpetas y archivos individuales.',
        'content': 'Contenido',
        'modification': 'Modificación',
        'permissions': 'Permisos',
        'empty_folder': 'Esta carpeta está vacía.',
        'recent_activity': 'Actividad Reciente',
        'no_activity': 'No hay actividad reciente registrada.',
        'user': 'Usuario',
        'settings': 'Configuración',
        'logout': 'Cerrar Sesión',
        'new_folder_title': 'Nueva Carpeta',
        'new_folder_desc': 'Ingresa un nombre para tu nueva carpeta.',
        'cancel': 'Cancelar',
        'create': 'Crear',
        'new_project_title': 'Nuevo Proyecto',
        'new_project_desc': 'Ingresa un nombre para tu nuevo proyecto.',

        // Navigation & Views
        'nav_engineering': 'Ingeniería',

        // Hero Section
        'hero_badge': 'Plataforma para subcontratistas, técnicos e ingenieros',
        'hero_title_1': 'Gana más proyectos cotizando',
        'hero_title_2': 'con precisión y velocidad',
        'hero_title_3': 'usando IA',
        'hero_desc': 'Deja de perder horas en Excel. Genera metrados y presupuestos técnicos automáticos para HVAC, Eléctrica, iluminaria, entre otras areas. Cierra tratos 3x más rápido.',
        'hero_cta_demo': 'Agendar demo',
        'hero_cta_access': 'Vista técnica de la plataforma',
        'hero_footer': 'Orbitar permite generar presupuestos técnicos confiables y rápidos a partir de planos y documentación, utilizando automatización e inteligencia artificial.',

        // Business Description
        'business_title': '¿Qué es Orbitar?',
        'business_summary': 'Orbitar es una plataforma que actúa como el copiloto. Centralizamos datos dispersos y automatizamos la creación de documentación de alto valor, donde tú gestionas y controlas el proceso.',
        'business_desc_1': 'Crea presupuestos, cotizaciones y documentación técnica profesional de forma automática y trazable.',
        'business_desc_2': 'Elimina el error manual y estandariza la calidad de tus documentos, asegurando coherencia técnica y precisión.',
        'business_desc_3': 'Especializado en subcontratistas de Electricidad, Climatización (HVAC), Sanitarias y Sistemas Especiales. Tu oficina técnica, potenciada.',
        'business_disclaimer': 'Usa tu información (Excel, PDF, DWG, ETC.) para reducir tiempos y gestionar tus presupuestos o documentación profesional eficientemente.',

        // Problem Solution
        'prob_title': 'El problema que identificamos',
        'prob_desc': 'Los procesos de presupuestación o de documentos presentan desafíos operativos críticos y costosos.',
        'prob_point_1': 'Información dispersa y desordenada que aturde los procesos.',
        'prob_point_2': 'Procesos repetitivos, manuales y falta de estandarización técnica.',
        'prob_point_3': 'Inconsistencias entre documentos y alto riesgo de errores técnicos.',
        'sol_title': 'La solución: Orbitar',
        'sol_desc': 'Orbitar centraliza tus datos y elimina el caos de versiones de Excel, reduciendo errores manuales en un 90%.',
        'sol_point_1': 'Archivos y Datos Locales: Lectura directa de tus carpetas, Excel y documentos técnicos.',
        'sol_point_2': 'Uso de múltiples fuentes de datos como los de (WhatsApp, Drive, Local) usando APIS.',
        'sol_point_3': 'Ingeniería con CAD: Aprovechamiento de datos técnicos desde archivos CAD (DWG).',

        // Architecture Section (Flujo: Chat -> Repo -> Home)
        'arch_title': 'Cómo funciona Orbitar',
        'arch_desc': 'Tecnología de procesamiento inteligente: Estandarización y precisión total para transformar tu data en documentos técnicos de alto valor.',
        'arch_chat_title': '1. Carga y Lectura Profunda',
        'arch_chat_desc': 'Motor de lectura de archivos de alta eficiencia, donde el procesamiento instantáneo de data ejecuta y estandariza la documentación de calidad.',
        'arch_home_title': '2. Repositorio Estructurado',
        'arch_home_desc': 'Tu información se organiza automáticamente. La "Fuente Única de Verdad" que asegura que todo lo generado cumpla estricta coherencia técnica.',
        'arch_repo_title': '3. Gestión con Copiloto',
        'arch_repo_desc': 'Una vez estandarizado tu documento puedes perfeccionar y ajustar en tiempo real tu documentación, puliendo cada entregable.',

        // Product Status & Specs
        'status_title': 'Estándares Técnicos y Profesionalismo en tus Entregables',
        'status_desc': 'Orbitar simplifica la creación de cotizaciones, presupuestos y documentación técnica con resultados profesionales. La plataforma organiza automáticamente tu información siguiendo prácticas y estándares utilizados en proyectos reales.',
        'status_item_1': 'Entregables estructurados y profesionales',
        'status_item_2': 'Reducción del 70% en tiempos de entrega',
        'status_item_3': 'Documentación 100% libre de errores de cálculo',
        'status_item_4': 'Cumplimiento de prácticas técnicas internacionales',
        'status_item_5': 'Redacción técnica clara y profesional',
        'status_item_6': 'Documentación alineada a requisitos de seguridad y calidad',

        // Specialized Documentation
        'modules_title': 'Tipos de documentación',
        'modules_desc': 'Especializados en documentación, presupuestación y cotización para subcontratistas e ingenieros. Todo exportable a PDF y reutilizable para crear una biblioteca viva de conocimiento.',
        'mod_budget': 'Presupuestos',
        'mod_budget_desc': 'Tablas basadas en Excel real. Partidas, precios unitarios y metrados exactos.',
        'mod_memory': 'Metrados',
        'mod_memory_desc': 'Cómputos métricos exactos y detallados extraídos automáticamente de tus planos.',
        'mod_philosophy': 'Cotizaciones',
        'mod_philosophy_desc': 'Generación de cotizaciones detalladas con análisis de costos y precios unitarios.',
        'mod_view_more': 'Informes, Especificaciones, Memorias descriptivas, \nhoja tecnica y más...',
        'mode_label': 'Modo',
        'card_budget_total': 'MONTO TOTAL DEL PRESUPUESTO',
        'card_memory_analyzing': 'Analizando RNE...',
        'card_metrado_title': 'Resumen de Metrados',
        'card_metrado_item_1': 'Muro de Ladrillo',
        'card_metrado_value_1': '150.20 m²',
        'card_metrado_item_2': 'Concreto f\'c=210',
        'card_metrado_value_2': '45.50 m³',
        'card_phil_obj': 'Análisis de Costos',
        'card_phil_analysis': 'Precios Unitarios',
        'card_phil_others': 'Condiciones Comerciales',
        'diag_gen_blocks': 'Generador de Bloques',
        'diag_client_inter': 'Interacción del Cliente',
        'diag_approve_reject': 'Aprobación y Rechazo',
        'diag_workflow_label': 'Flujo de trabajo',
        'or_separator': 'o',
        'repo_content_title': 'Contenido',
        'repo_content_desc': 'Repositorio Estructurado',
        'repo_document_title': 'Documento',
        'repo_document_empty': 'Vista de Documento',
        'minichat_welcome': 'Copiloto IA: ¿Qué ajustamos?',


        // FAQ Section
        'faq_title': 'Resolución de Preguntas',
        'faq_desc': 'Listado de las preguntas frecuentes con sus respuestas y canales para que la persona con dudas pueda preguntar.',
        'faq_q1': '¿Qué puedo lograr con Orbitar en mis proyectos?',
        'faq_a1': 'Puedes generar metrados, presupuestos, cotizaciones y documentación técnica en menos tiempo, reduciendo errores y mejorando la presentación profesional de tus propuestas.',
        'faq_q2': '¿Orbitar realmente calcula metrados y presupuestos automáticamente?',
        'faq_a2': 'Sí. Orbitar analiza planos, Excel, PDF y archivos técnicos para extraer información, calcular metrados y estructurar presupuestos de forma automatizada.',
        'faq_q3': '¿Para qué tipo de empresas o profesionales está diseñado Orbitar?',
        'faq_a3': 'Principalmente para subcontratistas de oficios técnicos como electricidad, climatización, instalaciones, mantenimiento y sistemas especiales. También puede ser utilizado por técnicos e ingenieros que gestionan documentación técnica.',
        'faq_q4': '¿Qué tipos de archivos puedo usar en la plataforma?',
        'faq_a4': 'Puedes trabajar con archivos como PDF, Excel, planos DWG y documentos técnicos, además de integrar información proveniente de WhatsApp, Google Drive y archivos locales mediante APIs.',
        'faq_q5': '¿Necesito experiencia en software complejo para usar Orbitar?',
        'faq_a5': 'No. La plataforma está diseñada para ser simple y guiada, permitiendo que puedas generar documentación técnica sin necesidad de conocimientos avanzados en sistemas.',
        'faq_q6': '¿Puedo editar los documentos antes de enviarlos a mis clientes?',
        'faq_a6': 'Sí. Puedes revisar, ajustar y personalizar presupuestos, metrados y cotizaciones antes de exportarlos o compartirlos.',
        'faq_q7': '¿Qué obtengo si solicito una demo o acceso temprano?',
        'faq_a7': 'Tendrás acceso anticipado a la plataforma, podrás probar sus funcionalidades antes del lanzamiento oficial y formar parte del grupo inicial de usuarios que influirá en mejoras y nuevas funciones.',

        // Team Section
        'team_title': 'Equipo Fundador',
        'founder_1_role': 'Co-fundador e Ingeniero Principal',
        'founder_1_desc': 'Arnie Fuertes. Egresado de Ingeniería de Software con especialización en IA (SENATI). Lidera desarrollo, UX-UI y Arquitectura.',
        'founder_2_role': 'Co-fundador',
        'founder_2_desc': 'Enrique Suárez. Fundador de CONAUTI SAC. Visión estratégica, redes de innovación e impulsor de alto nivel.',

        // Company
        'company_mention': 'Orbitar - Producto impulsado por CONAUTI SAC',
        'problem_badge': 'PROBLEMÁTICA Y SOLUCIÓN',
        'problem_section_title': 'Problemática Real',
        'company_title': 'El Copiloto de Ingeniería',
        'company_desc': 'Optimizamos la gestión operativa, automatizando la creación de todo tipo de documentación técnica y de presupuesto, eliminando la carga administrativa para que tu enfoque sea en la ejecucion.',
        'conauti_linkedin': 'CONAUTI LinkedIn',
        'files_label': 'ARCHIVOS',
        'files_total': 'archivos',
        'download_label': 'Descargar',
        'no_files': 'Sin archivos',
        'untitled_file': 'Archivo sin nombre',
        'confirm_delete': '¿Eliminar proyecto?',
        'download_started': 'Descargando...',

        // Contact
        'contact_title': 'Llamado a la acción (Validación)',
        'contact_label': 'Déjanos tus datos y conversemos:',
        'contact_phone': '+51 913 156 118 | +51 997 975 161',
        'contact_phone_arnie': '+51 913 156 118 (Arnie Fuertes)',
        'contact_phone_enrique': '+51 997 975 161 (Enrique Suárez)',
        'contact_email': 'esuarez.conauti@gmail.com',
        'contact_email_arnie': 'arniepaul489@gmail.com',
        'contact_email_enrique': 'esuarez.conauti@gmail.com',


        // Additional Sections
        'video_title': 'Vista técnica de la plataforma planteada',
        'hero_status_title': 'Estado del Proyecto',
        'hero_status': 'Orbitar está en fase de despliegue estratégico. Buscamos socios técnicos internacionales para optimizar procesos de ingeniería complejos.',

        // Footer
        'footer_desc': 'Plataforma de Documentación de Ingeniería para Empresas Proveedoras. Estándares Internacionales (ISO).',
        'footer_platform': 'Plataforma',
        'footer_repo': 'Repositorio',
        'footer_security': 'Seguridad',
        'footer_support': 'Soporte',
        'footer_docs': 'Documentación',
        'footer_status': 'Estado',
        'footer_header_product': 'Producto',
        'footer_header_project': 'Proyecto',
        'footer_header_nav': 'Navegación',
        'footer_link_vision': '¿Qué es Orbitar?',
        'footer_link_problem': 'Problema',
        'footer_link_how': 'Cómo funciona',
        'footer_link_docs': 'Documentación',
        'footer_link_status': 'Estándares ISO',
        'footer_link_faq': 'Preguntas Frecuentes',
        'footer_link_team': 'Equipo',
        'footer_link_video': 'Vista conceptual',
        'eng_ind': 'Ingeniería',
        'eng_elec': 'Ing. Eléctrica',
        'video_placeholder': 'Video Demo',
        'explore_functionality': 'Ver flujo de ingeniería',
        'dev_active_badge': 'Gestión de Calidad ISO',
        'footer_copyright': '© 2026 Orbitar. Todos los derechos reservados.',
        'footer_legal': 'Legal',
        'footer_privacy': 'Privacidad',
        'footer_terms': 'Términos',

        // Others
        'chat_back': 'volver',
        'access_btn': 'Agendar demo',
        'login_btn': 'Agendar demo',
        'chat_copy': 'Copiar',
        'chat_regenerate': 'Regenerar',
        'chat_loading': 'Analizando solicitud...',
        'chat_repo_loading': 'Procesando repositorio...',
        'chat_ai_name': 'Orbitar AI',
        'doc_preview_title': 'Vista Previa: ',
        'ai_generating': 'GENERANDO...',
        'chat_error_initial': 'Error al procesar mensaje.',
        'chat_error_general': 'Error de conexión con IA.',
        'profile_label': 'Perfil',
        'back': 'Volver',
        'login_title': 'Documentación de ingeniería profesional',
        'login_subtitle': 'Plataforma para empresas proveedoras',
        'continue_google': 'Google',
        'continue_apple': 'Apple',
        'continue_email': 'Email',
        'email_placeholder': 'Correo electrónico',
        'continue': 'Continuar',
        'terms_text_1': 'Aceptas las',
        'terms': 'Condiciones',
        'terms_text_2': 'y',
        'privacy': 'Política de privacidad',
        'image_placeholder': 'Imagen',
        'use_microphone': 'Micrófono',
        'more_options': 'Opciones',
        'attach_menu': 'Adjuntar',
        'example_project_name': 'Ej. Planta Industrial'
    },
    'en': {
        // Chat Overlay
        'my_projects': 'My Projects',
        'manage_workspaces': 'Manage and create new workspaces.',
        'create_project': 'Create Project',
        'no_projects': 'No projects created yet.',
        'new': 'New',
        'library': 'Library',
        'no_projects_sidebar': 'No projects',
        'new_folder_sidebar': 'Create Project',
        'storage': 'Storage',
        'new_chat': 'New Chat',
        'history': 'History',
        'no_history': 'No recent history',
        'ask_anything': 'Ask anything...',
        'upload_files': 'Upload files',
        'search_projects': 'Search projects by name',
        'add_kpi': 'Add KPI',
        'search_file': 'Search folder or file by name',
        'navigation': 'Navigation',
        'home': 'Home',
        'filter': 'Filter',
        'click_upload': 'Click here to upload your file or drag folder.',
        'supports_files': 'Supports folders and individual files.',
        'content': 'Content',
        'modification': 'Modification',
        'permissions': 'Permissions',
        'empty_folder': 'This folder is empty.',
        'recent_activity': 'Recent Activity',
        'no_activity': 'No recent activity registered.',
        'user': 'User',
        'settings': 'Settings',
        'logout': 'Log Out',
        'new_folder_title': 'New Folder',
        'new_folder_desc': 'Enter a name for your new folder.',
        'cancel': 'Cancel',
        'create': 'Create',
        'new_project_title': 'New Project',
        'new_project_desc': 'Enter a name for your new project.',

        // Navigation & Views
        'nav_engineering': 'Engineering',

        // Hero Section
        'hero_badge': 'B2B SaaS for engineering service provider companies',
        'hero_title_1': 'Upload, Generate and Manage',
        'hero_title_2': 'engineering documentation with AI',
        'hero_status': 'Orbitar is in strategic deployment phase. We are looking for international technical partners to optimize complex engineering processes.',
        'hero_desc': 'Automate takeoffs and budgets from your data or provided information and generate ready-to-use quotes in less time.',
        'access_btn': 'Schedule demo',
        'login_btn': 'Schedule demo',
        'hero_cta_demo': 'Schedule demo',
        'hero_cta_access': 'Technical View of the Platform',
        'hero_used_for': 'FROM RAW DATA TO DELIVERABLES',

        // Business Description
        'business_title': 'What is Orbitar?',
        'business_summary': 'Orbitar is a platform that acts as the engineer\'s copilot. We centralize dispersed data and automate the creation of high-value documentation, where you manage and control the process.',
        'business_desc_1': 'Automatically and traceably create professional documentation (proposals, budgets, technical sheets, among others).',
        'business_desc_2': 'Eliminate manual error and standardize the quality of your documents, ensuring technical coherence and precision.',
        'business_desc_3': 'Ideal for civil, electrical, and mechanical engineering and complex projects seeking automation.',
        'business_disclaimer': 'Use your information (Excel, PDF, DWG, etc.) to reduce times and manage professional documentation efficiently.',

        // Problem Solution
        'prob_title': 'The problem we identified',
        'prob_desc': 'Engineering documentation presents critical and costly operational challenges.',
        'prob_point_1': 'Use of multiple unstructured data sources (WhatsApp, Drive, Local).',
        'prob_point_2': 'Repetitive, manual processes and lack of technical standardization.',
        'prob_point_3': 'Inconsistencies between documents and high risk of technical errors.',
        'sol_title': 'The solution: Orbitar',
        'sol_desc': 'Orbitar centralizes your data to standardize the generation and management of engineering documents.',
        'sol_point_1': 'Local Files and Data: Direct reading of your folders, Excel, and technical documents.',
        'sol_point_2': 'Operational Channels: Integration with Drive, Office and enterprise messaging to centralize your data.',
        'sol_point_3': 'Engineering with CAD: Leveraging technical data from CAD files (DWG).',

        // Architecture Section (Flow: Chat -> Repo -> Home)
        'arch_title': 'How Orbitar Works',
        'arch_desc': 'Intelligent processing technology: Standardization and total precision to transform your data into high-value engineering.',
        'arch_chat_title': '1. Load and Deep Reading',
        'arch_chat_desc': 'High-efficiency file reading engine, where instantaneous data processing executes and standardizes quality documentation.',
        'arch_home_title': '2. Structured Repository',
        'arch_home_desc': 'Your information is automatically organized. The "Single Source of Truth" that ensures everything generated maintains strict technical coherence.',
        'arch_repo_title': '3. Management with Copilot',
        'arch_repo_desc': 'Once your document is standardized, you can refine and adjust your documentation in real-time, polishing every deliverable.',

        // Product Status & Specs
        'status_title': 'International Standards and Quality',
        'status_desc': 'Orbitar is based on the ISO 9001 standard for quality management and operation. We ensure that every deliverable meets the highest international engineering standards.',
        'status_item_1': 'ISO 9001:2015 - Quality Management',
        'status_item_2': 'Standards (ASTM, IEEE, NFPA)',
        'status_item_3': 'Compliance Management',
        'status_item_4': 'Global Technical Specifications',
        'status_item_5': 'Technical-Formal Language',
        'status_item_6': 'Security according to standards',

        // Specialized Documentation
        'modules_title': 'Documentation types',
        'modules_desc': 'Specialized in engineering text documentation. Everything exportable to PDF and reusable to create a living library of knowledge.',
        'mod_budget': 'Engineering Budgets',
        'mod_budget_desc': 'Tables based on real Excel. Items, unit prices, and exact measurements.',
        'mod_memory': 'Descriptive Memories',
        'mod_memory_desc': 'Technical justification of decisions, with formal and normative language.',
        'mod_philosophy': 'Technical Proposals',
        'mod_philosophy_desc': 'Comprehensive definition of objectives, scope, methodology, and timeline (Technical-Economic).',
        'mod_view_more': 'Reports, Specifications, and more...',
        'mode_label': 'Mode',
        'card_budget_total': 'TOTAL BUDGET AMOUNT',
        'card_memory_analyzing': 'Analyzing...',
        'card_phil_obj': 'Technical Objectives',
        'card_phil_analysis': 'Normative Analysis',
        'card_phil_others': 'Specifications...',
        'diag_gen_blocks': 'Block Generator',
        'diag_client_inter': 'Client Interaction',
        'diag_approve_reject': 'Approval and Rejection',
        'diag_workflow_label': 'Workflow',
        'or_separator': 'or',
        'repo_content_title': 'Content',
        'repo_content_desc': 'Structured Repository',
        'repo_document_title': 'Document',
        'repo_document_empty': 'Document View',
        'minichat_welcome': 'AI Copilot: What shall we adjust?',

        // Team Section
        'team_title': 'Founding Team',
        'founder_1_role': 'Co-founder and Lead Engineer',
        'founder_1_desc': 'Arnie Fuertes. Software Engineering graduate specialized in AI (SENATI). Leads development, UX-UI, and Architecture.',
        'founder_2_role': 'Co-founder',
        'founder_2_desc': 'Enrique Suárez. Founder of CONAUTI SAC. Strategic vision, innovation networks, and high-level driver.',

        // Company
        'company_mention': 'Orbitar - Product driven by CONAUTI SAC',
        'problem_badge': 'PROBLEM AND SOLUTION',
        'problem_section_title': 'Real Problem',
        'company_title': 'The Engineering Copilot',
        'company_desc': 'We optimize operational management, automating the creation of all types of technical documentation and complex dossiers, eliminating the administrative burden so your team focuses on high-value design and decisions.',
        'conauti_linkedin': 'CONAUTI LinkedIn',
        'files_label': 'FILES',
        'files_total': 'files',
        'download_label': 'Download',
        'no_files': 'No files',
        'untitled_file': 'Untitled file',
        'confirm_delete': 'Delete project?',
        'download_started': 'Downloading...',

        // Contact
        'contact_title': 'Call to Action (Validation)',
        'contact_label': 'Leave us your details and let\'s talk:',
        'contact_phone': '+51 913 156 118 | +51 997 975 161',
        'contact_phone_arnie': '+51 913 156 118 (Arnie Fuertes)',
        'contact_phone_enrique': '+51 997 975 161 (Enrique Suárez)',
        'contact_email': 'esuarez.conauti@gmail.com',
        'contact_email_arnie': 'arniepaul489@gmail.com',
        'contact_email_enrique': 'esuarez.conauti@gmail.com',

        // Footer
        'footer_desc': 'Engineering Documentation Platform for Provider Companies. International Standards (ISO).',
        'footer_platform': 'Platform',
        'footer_repo': 'Repository',
        'footer_security': 'Security',
        'footer_support': 'Support',
        'footer_docs': 'Documentation',
        'footer_status': 'Status',
        'footer_header_product': 'Product',
        'footer_header_project': 'Project',
        'footer_header_nav': 'Navigation',
        'footer_link_vision': 'What is Orbitar?',
        'footer_link_problem': 'Problem',
        'footer_link_how': 'How it works',
        'footer_link_docs': 'Documentation',
        'footer_link_status': 'ISO Standards',
        'footer_link_faq': 'FAQ',
        'footer_link_team': 'Team',
        'footer_link_video': 'Conceptual View',
        'eng_ind': 'Engineering',
        'eng_elec': 'Elec. Eng.',
        'eng_mech': 'Mech. Eng.',
        'video_title': 'Platform Conceptual View',
        'video_placeholder': 'Video Demo',
        'explore_functionality': 'View engineering flow',
        'dev_active_badge': 'ISO Quality Management',
        'footer_copyright': '© 2026 Orbitar. All rights reserved.',
        'footer_legal': 'Legal',
        'footer_privacy': 'Privacy',
        'footer_terms': 'Terms',

        // Others
        'chat_back': 'back',
        'chat_copy': 'Copy',
        'chat_regenerate': 'Regenerate',
        'chat_loading': 'Analyzing request...',
        'chat_repo_loading': 'Processing repository...',
        'chat_ai_name': 'Orbitar AI',
        'doc_preview_title': 'Preview: ',
        'ai_generating': 'GENERATING...',
        'chat_error_initial': 'Error processing message.',
        'chat_error_general': 'Connection error with AI.',
        'profile_label': 'Profile',
        'back': 'Back',
        'login_title': 'Professional engineering documentation',
        'login_subtitle': 'Platform for provider companies',
        'continue_google': 'Google',
        'continue_apple': 'Apple',
        'continue_email': 'Email',
        'email_placeholder': 'Email address',
        'continue': 'Continue',
        'terms_text_1': 'You agree to',
        'terms': 'Terms',
        'terms_text_2': 'and',
        'privacy': 'Privacy Policy',
        'image_placeholder': 'Image',
        'use_microphone': 'Microphone',
        'more_options': 'Options',
        'attach_menu': 'Attach',
        'example_project_name': 'Eg. Industrial Plant'
    }
};
